services:
  - type: web
    name: my-web-app
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    branch: main
    autoDeploy: true
    pullRequestPreviewsEnabled: true
    envVars:
      - key: NODE_ENV
        value: production
